FROM --platform=linux/x86_64 python:3.11

RUN apt-get update && \
    apt-get install -y git cmake wget make libncurses-dev flex bison gperf libusb-1.0-0 libusb-1.0-0-dev

WORKDIR /opt/app

ENV PATH=${PATH}:/root/.local/bin

RUN git clone https://github.com/micropython/micropython && \
    git clone -b v4.4.5 --recursive https://github.com/espressif/esp-idf.git && \
    cd esp-idf && \
    bash /opt/app/esp-idf/install.sh && \
    bash -c "source export.sh" && \
    cd /opt/app/micropython && \
    git checkout v1.20.0 && \
    git submodule update --init && \
    pip install -U pip && \
    pip install pyparsing==2.3.1 && \
    pip install esptool==3.0 && \
    pip install pyserial==3.5 && \
    pip install 'click>=7.0' \
    'future>=0.15.2' \
    'pyelftools>=0.22' \
    'idf-component-manager~=1.2' \
    'urllib3<2' \
    'pygdbmi<=0.9.0.2' \
    'kconfiglib==13.7.1' \
    'bitstring>=3.1.6,<4' \
    'construct==2.10.54'

ENV ESPIDF "/opt/app/esp-idf"
ENV IDF_PATH "/opt/app/esp-idf"
ENV BOARD "MDNS"

RUN python "${IDF_PATH}/tools/idf_tools.py" export && \
    python "${IDF_PATH}/tools/check_python_dependencies.py"

ADD config/boards/ /opt/app/micropython/ports/esp32/boards/

WORKDIR /opt/app/micropython

RUN make -C mpy-cross

WORKDIR /opt/app/micropython/ports/esp32

RUN bash -c "source ${IDF_PATH}/export.sh && make submodules && make"

WORKDIR /opt/app/

WORKDIR /opt/app/micropython/ports/esp32

ADD src/mdns_client modules/mdns_client

RUN bash -c "source ${IDF_PATH}/export.sh && make"
